"""Static species/move lookup tables (bundled JSON) for display.

Generated by tools/gen_data.py from pokeemerald-expansion. The internal species
enum only matches National-Dex order up to ~905; Gen-9 mons and Mega/regional
forms are appended at higher ids, so nat_dex.json maps internal id -> National-Dex
number (used for PokeAPI sprites and the generation badge).
"""
import json
import os

REPO_DATA = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data")


class PokeData:
    def __init__(self, data_dir=REPO_DATA):
        self.species = self._load(data_dir, "species.json")
        self.moves = self._load(data_dir, "moves.json")
        self.abilities = self._load(data_dir, "abilities.json")
        self.items = self._load(data_dir, "items.json")
        self.nat_dex = self._load(data_dir, "nat_dex.json")

    @staticmethod
    def _load(data_dir, name):
        try:
            with open(os.path.join(data_dir, name), encoding="utf-8") as fh:
                return json.load(fh)
        except (FileNotFoundError, ValueError):
            return {}

    def species_name(self, species_id):
        return self.species.get(str(species_id))

    def national_dex(self, species_id):
        """National-Dex number for an internal species id (forms -> base's dex).
        Falls back to the id itself when it's already a valid dex number."""
        n = self.nat_dex.get(str(species_id))
        if n:
            return n
        return species_id if 1 <= species_id <= 1025 else None

    def move(self, move_id):
        return self.moves.get(str(move_id))

    def ability_name(self, ability_id):
        return self.abilities.get(str(ability_id))

    def item_name(self, item_id):
        return self.items.get(str(item_id))
