"""Static species/move lookup tables (bundled JSON) for display.

Generated by tools/gen_data.py from pokeemerald-expansion. Lazarus uses the
default expansion National-Dex numbering, so these resolve its IDs directly.
"""
import json
import os

REPO_DATA = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data")


class PokeData:
    def __init__(self, data_dir=REPO_DATA):
        self.species = self._load(data_dir, "species.json")
        self.moves = self._load(data_dir, "moves.json")

    @staticmethod
    def _load(data_dir, name):
        try:
            with open(os.path.join(data_dir, name), encoding="utf-8") as fh:
                return json.load(fh)
        except (FileNotFoundError, ValueError):
            return {}

    def species_name(self, species_id):
        return self.species.get(str(species_id))

    def move(self, move_id):
        return self.moves.get(str(move_id))
